import type { Metadata } from "next";
import { Inter, Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import Image from "next/image";
import backgroundImg from "../../public/images/bg_image.png";
import FooterNav from "@/app/components/FooterNav";
import ReactQueryProviders from "@/utils/ReactQueryProvider";
import { Toaster } from "@/components/ui/toaster";
import { QueryClientProvider } from "@tanstack/react-query";
import Script from "next/script";
import { useEffect } from "react";
import KakaoScript from "./result/components/KakaoScript";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const notoSansKr = Noto_Sans_KR({
  weight: ["500"],
  subsets: ["latin"],
});

declare global {
  interface Window {
    Kakao: any;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex items-center justify-center min-w-[450px] relative">
          <Image
            src={backgroundImg}
            alt="Background"
            fill
            quality={100}
            priority
            style={{
              zIndex: -1,
              objectFit: "cover",
            }}
          />
          <div className="flex items-center justify-center w-full h-full bg-black bg-opacity-60">
            <main className="flex flex-col h-screen w-[450px]">
              <Header />
              <ReactQueryProviders>
                <div className="flex h-full w-full bg-[#ffffff] overflow-y-auto justify-center">
                  {children}
                </div>
              </ReactQueryProviders>
              <div className="border"></div>
              <FooterNav />
            </main>
          </div>
        </div>
        <Toaster />
      </body>
      <KakaoScript />
    </html>
  );
}
