import type { Metadata } from "next";
import { Inter, Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Image from "next/image";
import backgroundImg from "../../public/images/bg_image.png";
import FooterNav from "@/components/FooterNav";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const notoSansKr = Noto_Sans_KR({
  weight: ["500"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex items-center justify-center">
          <Image
            src={backgroundImg}
            alt="Background"
            layout="fill"
            objectFit="cover"
            quality={100}
            priority
            style={{ zIndex: -1 }}
          />
          <div
            className="flex items-center justify-center w-full h-full bg-black bg-opacity-50"
            style={{ zIndex: 1 }}
          >
            <main className="flex flex-col h-screen rounded-md">
              <Header />
              {/* <div className="border"></div> */}
              <div className="h-screen bg-[#ffffff] overflow-y-auto flex justify-center w-[600px]">
                {children}
              </div>
              {/* TODO: main이랑 footer랑 분리 */}
              <div className="border"></div>
              <FooterNav />
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
